baseURL = "https://dpfg.netlify.app/"
languageCode = "en-us"
title = "/home/dpfg"
theme = "cactus"
copyright = "dpfg"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false

[params]
  colortheme = "classic" # dark, light, white, or classic
  rss = true
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your websiteâ€™s end users and an ideal writing experience for website authors."
  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = false
  showProjectsList = true
  projectsUrl = "https://github.com/dpfg"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/dpfg"
  [[params.social]]
    name = "email"
    link = "xander.blr@gmail.com"